presta_sitemap:
    default_section: default
    defaults:
        priority: 1
        changefreq: daily
        lastmod: now
    alternate:
        enabled: true
        default_locale: 'fr'
        locales: [ 'en', 'fr' ]
        i18n: symfony
